"""initial migration

Revision ID: a14fd64d977b
Revises: 
Create Date: 2026-01-01 16:23:48.654335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14fd64d977b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture',
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.Column('rapid_api_id', sa.Integer(), nullable=False),
    sa.Column('kick_off', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('home_team_logo', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('away_team_logo', sa.String(length=255), nullable=False),
    sa.Column('home_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draw_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_id'), 'fixture', ['id'], unique=False)
    op.create_table('job_control',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_control_id'), 'job_control', ['id'], unique=False)
    op.create_index(op.f('ix_job_control_job_name'), 'job_control', ['job_name'], unique=True)
    op.create_table('league',
    sa.Column('rapid_api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_id'), 'league', ['id'], unique=False)
    op.create_table('user',
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cognito_uuid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_cognito_uuid'), 'user', ['cognito_uuid'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('bet',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('choice', sa.String(length=5), nullable=False),
    sa.Column('stake', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('returns', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_id'), 'bet', ['id'], unique=False)
    op.create_table('transaction_record',
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('bet_id', sa.String(length=36), nullable=False),
    sa.Column('user_balance_before', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('user_balance_after', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_record_id'), 'transaction_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_record_id'), table_name='transaction_record')
    op.drop_table('transaction_record')
    op.drop_index(op.f('ix_bet_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_cognito_uuid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_league_id'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_job_control_job_name'), table_name='job_control')
    op.drop_index(op.f('ix_job_control_id'), table_name='job_control')
    op.drop_table('job_control')
    op.drop_index(op.f('ix_fixture_id'), table_name='fixture')
    op.drop_table('fixture')
    # ### end Alembic commands ###
