"""initial

Revision ID: 72b152bf1095
Revises: 
Create Date: 2026-07-10 15:51:59.363209

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b152bf1095'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cup',
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('final_entry_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_index(op.f('ix_cup_id'), 'cup', ['id'], unique=False)
    op.create_table('job_control',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_control_id'), 'job_control', ['id'], unique=False)
    op.create_index(op.f('ix_job_control_job_name'), 'job_control', ['job_name'], unique=True)
    op.create_table('league',
    sa.Column('rapid_api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_id'), 'league', ['id'], unique=False)
    op.create_table('user',
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cognito_uuid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_cognito_uuid'), 'user', ['cognito_uuid'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index('uq_user_username_lower', 'user', [sa.text('lower(username)')], unique=True)
    op.create_table('cup_entry',
    sa.Column('cup_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cup_id'], ['cup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cup_id', 'user_id', name='uq_cup_entry')
    )
    op.create_index(op.f('ix_cup_entry_id'), 'cup_entry', ['id'], unique=False)
    op.create_table('fixture',
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.Column('rapid_api_id', sa.Integer(), nullable=False),
    sa.Column('kick_off', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('home_team_logo', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('away_team_logo', sa.String(length=255), nullable=False),
    sa.Column('home_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draw_odds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_id'), 'fixture', ['id'], unique=False)
    op.create_table('pundit_usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_pundit_usage_user_day')
    )
    op.create_index(op.f('ix_pundit_usage_id'), 'pundit_usage', ['id'], unique=False)
    op.create_table('bet',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cup_entry_id', sa.String(length=36), nullable=False),
    sa.Column('choice', sa.String(length=5), nullable=False),
    sa.Column('stake', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('returns', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cup_entry_id'], ['cup_entry.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_id'), 'bet', ['id'], unique=False)
    op.create_table('ledger_entry',
    sa.Column('cup_entry_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('bet_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bet.id'], ),
    sa.ForeignKeyConstraint(['cup_entry_id'], ['cup_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entry_id'), 'ledger_entry', ['id'], unique=False)
    # ### end Alembic commands ###

    job_control = sa.table(
        "job_control",
        sa.column("id", sa.String(36)),
        sa.column("job_name", sa.String(64)),
        sa.column("enabled", sa.Boolean()),
        sa.column("min_interval_seconds", sa.Integer()),
        sa.column("last_run_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        job_control,
        [
            {
                "id": str(uuid4()),
                "job_name": name,
                "enabled": True,
                "min_interval_seconds": interval,
                "last_run_at": None,
            }
            for name, interval in [
                ("fetch_leagues", 86400),
                ("fetch_fixtures", 119),
                ("fetch_odds", 259),
                ("fetch_fixture_updates", 259),
                ("settle_bets", 59),
                ("settle_voided_bets", 59),
                ("close_cups", 300),
            ]
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entry_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_index(op.f('ix_bet_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_pundit_usage_id'), table_name='pundit_usage')
    op.drop_table('pundit_usage')
    op.drop_index(op.f('ix_fixture_id'), table_name='fixture')
    op.drop_table('fixture')
    op.drop_index(op.f('ix_cup_entry_id'), table_name='cup_entry')
    op.drop_table('cup_entry')
    op.drop_index('uq_user_username_lower', table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_cognito_uuid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_league_id'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_job_control_job_name'), table_name='job_control')
    op.drop_index(op.f('ix_job_control_id'), table_name='job_control')
    op.drop_table('job_control')
    op.drop_index(op.f('ix_cup_id'), table_name='cup')
    op.drop_table('cup')
    # ### end Alembic commands ###
