[mypy]
python_version = 3.12
mypy_path = src
files = src

warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
no_implicit_optional = True
check_untyped_defs = True
disallow_incomplete_defs = True

# Stage in later once annotations are in place
disallow_untyped_defs = False
disallow_any_generics = False

[mypy-authlib.*]
ignore_missing_imports = True

[mypy-sqladmin.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-requests]
ignore_missing_imports = True

[mypy-jose]
ignore_missing_imports = True
